name: esc_pos_bluetooth
description: The library allows to print receipts using an ESC/POS thermal Bluetooth printer.
version: 0.2.7
homepage: https://github.com/andrey-ushakov/esc_pos_bluetooth

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.26.0
  esc_pos-utils: 
    git:
      url: https://github.com/teewhydope/esc_pos_utils.git
  # esc_pos_utils:
    # path: ../esc_pos_utils
  flutter_bluetooth_basic: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
