name: blue
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  oktoast: ^2.3.0
  image: ^2.1.4
  esc_pos_bluetooth:
    path: ../../
  esc_pos_utils: ^0.3.6
  # esc_pos_utils:
    # path: ../../../esc_pos_utils
  charset_converter: ^1.0.3
  intl: ^0.16.1
  qr_flutter: ^3.2.0
  path_provider: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo216.png
    - assets/logo222.png
    - assets/rabbit_black.jpg
